### ISSUE TITLE
Corrections to instructions in top-level README

### ISSUE THREAD

**Issue by mandy-chessell** [odpi/egeria-database-connectors#106]
I tried to set up the postgres connector and noticed the following in the top level readme ...

* The connector is an "Integration connector" rather than a "integration daemon connector".
* There are no instructions on how to build the connector or where the resulting JAR is located
* Where is the postman collection referred to?
* "Egeria platform" should be "OMAG Server Platform" or "Egeria's OMAG Server Platform" to distinguish it from the "EgeriaUIPlatform".
* The urls for the HTTP requests have hard-coded platform URL root, server names and admin user id.  It would be helpful to either use placeholders - eg {serverName} - or point out the places where they have to substitute their values.
This is partly done, but garygeeke is not explained.
* Under "Postgres Connection Details" it begins "After creating the Egeria Integration Daemon server ..." However, at this point, details of creating the server are not covered and are never covered.
* "omagserverPlatformRootURL" is the hostname and port number for the OMAGServerPlatform that is hosting the metadata server that will store the metadata created by the postgres connector.
* "omagserverName" is the name of the metadata server hat will store the metadata created by the postgres connector.  It is running the Data Manager OMAS.
* "platformName" is the hostname there the platform hosting Integration Daemon runs and it is followed by the port number that the platform is listening on.
* On the example connection:
     * "connectorProviderClassName" should be "org.odpi.openmetadata.adapters.connectors.integration.postgres.PostgresDatabaseProvider"
     * "recognizedConfigurationProperties" are part of the "connectorType" not the connection - however they are not needed for configuration and can be removed.
     * There is no endpoint in the connection to take the database address.  I see configuration properties with the database URL.  However, it should be in the Endpoint with encryptionMethod set to SSL or not as required.  This is just to keep the set up of the connectors consistent.
* `metadataSourceQualifiedName` is the software server capability - not software server
* `usesBlockingCalls` requests  a separate thread for the connector to issue blocking calls - in this case use "false"
* `permittedSynchronization` indicates the direction that metadata is flowing - in this case the metadata is flowing from the database to Egeria and so use "FROM_THIRD_PARTY"
* Be useful to link to the pages for starting the integration daemon

**Comment by mandy-chessell** [comment]
Many links to the main Egeria documentation and diagrams are no longer working since the docs were migrated

**Comment by planetf1** [comment]
@wbittles I can take a look at this, as I'm using the connector currently. Let me know if you'd prefer to make the changes.

**Comment by wbittles** [comment]
@planetf1 
Sorting out the docs would be quite welcome if your happy to keep going with that.
I'll have a look at the scan results, and see if I can figure out what's up with David's use case.

**Comment by planetf1** [comment]
@wbittles Sure, I'll try and clarify. I've been setting up myself, and helping someone else do same, so it's probably a good perspective!

**Comment by wbittles** [comment]
@planetf1 I usually  follow Mandy's postman tutorials , it  covers all the steps, just need to change the relevant names.

**Comment by planetf1** [comment]
Closing - this repository is now being archived.
