### ISSUE TITLE
Update column type does not get reflected into Egeria

### ISSUE THREAD

**Issue by davidradl** [odpi/egeria-database-connectors#153]
Update column type does not get reflected into Egeria. The type was change from string length 20 to string length 25 but the change to not go through to Egeria. 

It looks like code in PostgresDatabaseConnector around line 883 should be uncommented then any follow-on issue debugged 
`                        if (egeriaColumn.getDatabaseColumnProperties().getQualifiedName().equals(postgresColumn.getQualifiedName()))
                            {
                            /*
                            we have found an exact instance to update
                             */
                                found = true;
                                //TODO
                             //   updateColumn(postgresColumn, egeriaColumn);
                                break;
                            }
`

**Comment by wbittles** [comment]
That doesn't look like the latest release of code @davidradl or it doesn't match my version.

**Comment by davidradl** [comment]
> That doesn't look like the latest release of code @davidradl or it doesn't match my version.

See [https://github.com/odpi/egeria-database-connectors/blob/main/egeria-connector-postgres/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresDatabaseConnector.java](https://github.com/odpi/egeria-database-connectors/blob/main/egeria-connector-postgres/src/main/java/org/odpi/openmetadata/adapters/connectors/integration/postgres/PostgresDatabaseConnector.java) . This is the latest in master and matches my comment. Is there more code that you have locally that could help here?

**Comment by wbittles** [comment]
That piece of code looks like it's from when I was unit testing the "addDatabase" branch which makes it at least two major release behind what I have. 
I unit tested the update and delete branches after this . 
I've just downloaded the latest version from git hub and it's not what your looking at ? 


`                  for (DatabaseElement egeriaDatabase : egeriaDatabases)
                    {

                        String egeriaQN =  egeriaDatabase.getDatabaseProperties().getQualifiedName();
                        String postgresQN = postgresDatabase.getQualifiedName();

                        if (egeriaQN.equals(postgresQN))
                        {
                        /*
                        we have found an exact instance to update
                         */
                            found = true;
                            updateDatabase(postgresDatabase, egeriaDatabase);
                            break;
                        }
                    }
                    /*
                    this is a new database so add it
                     */
                    if (!found)
                    {
                        addDatabase(postgresDatabase);
                    }
                }`

**Comment by planetf1** [comment]
@wbittles I see that code fragment you mentioned in 'UpdateViewColumns' method
The fragment @davidradl mentioned is in 'UpdateTableColumns' method

Can you clarify how the connector/postgres works with respect to tables/columns? Maybe the code is the same, and it's just our misunderstanding (I've not tested that code path myself)

**Comment by wbittles** [comment]
@planetf1 @davidradl  oops , I was looking at the doc for the database not updating
I have no idea why that code is like that , especially as the other call to that method isn't commented out.

**Comment by planetf1** [comment]
I'm using the connector currently, so
Happy to test the change for column update if you plan on updating, or I can try the code change.

**Comment by planetf1** [comment]
Closing - this repository is now being archived.
