### ISSUE TITLE
Questions around qualified name and the implementation of MySQL database connector

### ISSUE THREAD

**Issue by Kelukin** [odpi/egeria-database-connectors#177]
# Question One

Does the community recommend the user name the assets' qualified name by the pattern provided in the PostgreSQL connector? For example, the table's qualified name follows the pattern of `{{database_name}}::{{schema_name}}::(BASE|VIEW)::{{table_name}}`. In other words, will the community develop a overall standard for the assets' qualified name?

# Question Two

Unlike PostgreSQL, MySQL mixes the concept of database and schema. Hence, if we develop a MySQL database connector, should we still follow the pattern in Figure 2 of [Database Integrator](https://egeria-project.org/services/omis/database-integrator/overview/)? If we do, we will still create the assets of the database and schema, which disagree with the reality of MySQL.

By the way, when I tested this Egeria Database Connector, I found some bugs in the code. I will later create a pull request to fix them. Thanks.

**Comment by planetf1** [comment]
Comments in the concept of the new generic connector @lpalashevski @lcpopa  ?

**Comment by wbittles** [comment]
There are issues with the above naming scheme when the RDBMS provides a default database structure.
If you import two instances of the RDBMS then the default database name will causing conflicts in Egeria.
Adding a hostname/IP address should resolve that issue.

 @lpalashevski @lcpopa I'd be really interested in how the new connector is going to handle the different database structures, which is shared by the HiveMetastore.

**Comment by dwolfson** [comment]
@planetf1 As mentioned in another response, it is worth discussing if we should have separate connectors for database servers and databases. A database server (or server cluster) may contain many nodes and itself be distributed. There may be value in cataloging the server cluster characteristics including what schemas (if the database uses sql schemas) and databases hosted in the server cluster. A database connector would focus only on the details of a specific database. Note that this structure may also be helpful in public cloud situations where the details of the database cluster are managed by a service provider and the details of the database are managed by the tenant....

**Comment by planetf1** [comment]
Question One
---
There was a discussion on fully qualified names at the recent Egeria maintainer face2face meeting. We will be having a broader community discussion on naming strategies.

I suggest we keep this open until we've agreed a common strategy. We'll probably first concentrate on the generic jdbc connector, and then we can come back and update the postgres connector if it makes sense.

Question Two
---
For mysql - The generic JDBC integration & resource connectors have been developed recently. whilst they're not quite finished yet, I think testing them with mysql/mariadb could be really useful - and seeing what feedback there is. @Kelukin perhaps you'd like to help with this (I'm also going to do the same for IBM db2)?

**Comment by planetf1** [comment]
Closing - this repository is now being archived.
