### ISSUE TITLE
PostgreSQL cannot cannot create ForeignKey Links normally.

### ISSUE THREAD

**Issue by Kelukin** [odpi/egeria-database-connectors#183]
The PostgreSQL connector cannot create ForeignKey Links:

By diving into the code, I found these:
+ The RelationalColumn assets take `:: ` as a separator in the qualified name. But the previous implementation takes `.` as the separator to find column assets in creating foreign keys.
+ The connector cannot scan the schema 'public' normally because the logic in `isSchemaInUse` is a little bit wrong.
+ The loop in `addForeignKeys` has some mistakes in reinitializing the objects
+ the connector provider name should be `PostgresDatabaseProvider` instead of `postgresdatabaseprovider`, where the configuration cannot find the class with the latter setting.

**Comment by planetf1** [comment]
@dwolfson you may have thoughts on this as you've been using the connector recently? Were the keys all working ok after the fix was merged?

**Comment by dwolfson** [comment]
@planetf1 - I did a couple quick tests and validated that the foreign key relationships are now being picked up.

**Comment by planetf1** [comment]
Thanks @dwolfson - I think we can close this now
