### ISSUE TITLE
Top level readme needs to cater for multiple connectors

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-database-connectors#206]
This repo now contains both the postgres connector and the jdbc connector

As such the readme needs refactoring to either:
a) Move postgres content to a sub-section (lower level header) & add in a section for the database connector
b) Move all connector specifics out and push into a lower level readme,for postgres and jdbc

Since developers are typically working at the repository level, I'm more inclined to go with a hybrid ;-)

* Some content makes sense at the repo level
- what's in this repo (high level description)
- how to build the repo contents (gradle)
- What artifacts are created by a) gradle build b) ci/cd pipelines (build artifacts,  uploaded connector jar)

* More detailed specifics on configuration should either go into egeria docs, or if very technical probably in a component specific readme - but if small I think it's ok to just add in a section at top level

cc: @dwolfson @wbittles @lcpopa

Originally referenced at https://github.com/odpi/egeria-docs/pull/521

**Comment by dwolfson** [comment]
I think a hybrid approach makes sense - further, I suspect that the structure of the connector may split between one a database server connector that catalogs the server characteristics and schemas down to the database names/owners and database connectors that delve into a particular database (or a subset thereof) and catalog the databases characteristics. This would address a current issue with the Postgres connector where it tries to do both (I suspect this is also related to [https://github.com/odpi/egeria-database-connectors/issues/177#issuecomment-1195242810](url) )

**Comment by planetf1** [comment]
I think this has been done, additionally the jdbc connector has now moved to another repo
