### ISSUE TITLE
Add test environment for connector

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-database-connectors#5]
We need to test the postgres (and other) connectors against an egeria server. and using the integration server

Current offline testing uses:
1 zookeeper
2 kafka
3 postgres
4 integration daemon platform
5 metadata server platform

Ideally we would initiate this from github actions (PR or merge or .. later.. release). An external k8s cluster would need
funding, maint so I propose to initially look at a kind (kubernetes in docker) approach.

Actions found so far:
 - https://github.com/marketplace/actions/kind-kubernetes-in-docker-action
 - https://github.com/marketplace/actions/kind-cluster
 - https://github.com/marketplace/actions/kubernetes-kind-cluster

There are also a few actions using minikube or other approaches.

The existence of multiple actions suggest this is probably a viable approach worth persuing.

We could either deploy individual k8s deployment scripts, or compose into a helm chart

**Comment by planetf1** [comment]
- [ ] Add simple k8s action to prove we can create a k8s cluster
 - [ ] create simple deployment of a container
 - [ ] work on helm chart or k8s scripts for postgres connector testing
 - [ ] add chart/scripts to github action
 
Will consider how to run specific tests later

**Comment by planetf1** [comment]
The related PR wll now deploy a test helm chart to a kind cluster.
It does not yet wait for the pods to be ready, nor kick off any configuration of egeria servers
Orchestrating this is the next step, be it via jobs, helm tests, or other.

**Comment by planetf1** [comment]
See example test run so far at https://github.com/odpi/egeria-database-connectors/runs/1364709078?check_suite_focus=true

**Comment by planetf1** [comment]
After verbal review the next steps are:
 - [ ] Ensure helm chart/script waits until all containers are running
 - [ ] Add built connector onto the integration platform - depends on https://github.com/odpi/egeria/issues/4001
 - [ ] ? preload postgres database with data (example) ?
 - [ ] ? configure 1 server on each platform (example) ? 
 - [ ] ? look at options for orchestrating test cases (initially a script is sufficient)

**Comment by planetf1** [comment]
Added '--wait' to the helm chart install, so the script now pauses until all the pods are marked healthy (currently this is when their main ports are active -- we are not checking for servers being active, as we don't configure any yet).

**Comment by planetf1** [comment]
Reopening as it is still relevant to do this once we have a working version of the connector

**Comment by planetf1** [comment]
this is still needed - in fact the pipeline is in place
Just need to actually invoke the required tests

**Comment by planetf1** [comment]
With the latest code in place, we should have the basics to start moving forward with something like this

**Comment by planetf1** [comment]
as per discussion - feel free to assign back if you need a hand with the test infra.

**Comment by wbittles** [comment]
It's still not clear how anyone would run the CTS in this KIND environment  , can you please provide the details on how to achieve this

**Comment by planetf1** [comment]
The idea of the kind environment was to setup the base infrastructure to run tests against, not in itself to run a test harness.

Currently we have FVTs run within the build that are relatively simple - they 
 * launch a platform
 * wait until it's ready
 * Run a groovy script to configure the platform via REST calls
 * Run required java tests using the maven failsafe plugin (on maven - we do similar in gradle)
 * stop/cleanup the platform
 
 This takes a little bit of complexity to sequence, but not too bad - just a case of saving bids, checking ports etc.
 
 However some tests I anticipate being more complex, with more 'infrastructure' needed. For example with CTS we not only need 2 servers (server under test & the driving server) on a platform, but also need kafka and zookeeper to be launched.
 
 In the case of testing something like a postgres connector we'd likely need 1 or more servers on platform, kafka, zookeeper, and then ALSO an instance of a database -- as an example.
 
 The kind approach tries to cover this by
  - being able to run as a step in a github action (integrated, 'free', in-line with PR (or merge/release if needed) process) 
  - being able to easily re-use pre-existing assets ie containers for kafka, zookeeper, postgres etc (and of course egeria)
  - makes use (for egeria) of an existing supported asset (egeria container)
  - is aligned with at least one key way we expect egeria to be deployed (container, extensible, + k8s)
  - relatively easy to express topology via a helm chart definition (could be reusable or unique)
  - gets everything we want running in a clear simple step
  
  We still need to 
   - configure the platform/servers : this could be done within the chart definition as a k8s job (for example) or could be driven by an external test driver. I'd err towards the former, but the latter is perfectly fine too. May be a mix (in future the operator could do some of this too - but we're not there yet)
    - execute/drive the tests. We could try and re-use failsafe etc. In CTS case our own Java code performs this role, but there are various other test frameworks out there which may make it easier.
    
  Hope that explains the thoughts behind this approach.

**Comment by planetf1** [comment]
Can consider this alongside/once #58
