### ISSUE TITLE
fix the misleading quality gates linked from the readme

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria-database-connectors#70]
we need to fix the cut and paste error at the top of the readme. 

Egeria Logo
GitHub CII Best Practices Azure Quality Gate Status Maven Central

however not until we understand the the differences between the scans.

**Comment by planetf1** [comment]
I've added a PR to improve - 
* The azure link is not relevant for the connector (in fact not really for the base either - where it has already been removed)
* The quality gate is always showing red as we've not set appropriate rules/strategy for the sonar reports - it is removed in the base so done the same here

I've left the maven link as is, but note it points to a group, not artifact. this is egeria as a whole (and that is what the version is of). If diversions diverge the actual connector may not be found in that version. In any case only one artifact is chosen not the 100s we have in the base. So at best it's an invite to go looking. As such it's probably worth leaving as-is.

**Comment by planetf1** [comment]
Still a rogue ) in the readme!
